#!/usr/bin/env python3
"""
Build script: combines all question data into docs/ for GitHub Pages deployment.
Run: python scripts/build.py
Output: docs/questions.js + docs/index.html
"""
import json, os, glob, shutil

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(BASE, "docs")
os.makedirs(DOCS, exist_ok=True)

# Domain metadata
DOMAINS = {
    "psychopharm": {"label": "Психофармакология", "icon": "💊", "color": "#E85D04"},
    "mood": {"label": "Аффективные расстройства", "icon": "🌊", "color": "#2196F3"},
    "psychosis": {"label": "Психотические расстройства", "icon": "🔮", "color": "#9C27B0"},
    "anxiety": {"label": "Тревога / ОКР / ПТСР", "icon": "⚡", "color": "#4CAF50"},
    "substance": {"label": "Наркология", "icon": "🧪", "color": "#FF5722"},
    "personality": {"label": "Расстройства личности", "icon": "🎭", "color": "#E91E63"},
    "neurocognitive": {"label": "Нейрокогнитивные", "icon": "🧠", "color": "#795548"},
    "forensic": {"label": "Право и этика", "icon": "⚖️", "color": "#607D8B"},
    "evaluation": {"label": "Диагностика и оценка", "icon": "🔍", "color": "#009688"},
    "child": {"label": "Детская психиатрия", "icon": "🧒", "color": "#FF9800"},
    "development": {"label": "Психология развития", "icon": "📈", "color": "#8BC34A"},
    "biosciences": {"label": "Нейронауки", "icon": "🔬", "color": "#00BCD4"},
    "psychotherapy": {"label": "Психотерапия", "icon": "🗣️", "color": "#673AB7"},
}

all_questions = []

# Load PreTest
pretest_dir = os.path.join(BASE, "data", "pretest")
pt_count = 0
if os.path.exists(pretest_dir):
    for f in sorted(glob.glob(os.path.join(pretest_dir, "*.json"))):
        data = json.load(open(f, encoding='utf-8'))
        domain = os.path.basename(f).replace('.json', '')
        for q in data:
            all_questions.append({
                "id": q["id"],
                "domain": q.get("domain", domain),
                "source": "pretest",
                "difficulty": 2,
                "vignette": q["vignette"],
                "question": "Select the best answer.",
                "options": q["options"],
                "correct": q["correct"],
                "explanation_text": q.get("explanation", ""),
                "explanations": None,
                "pearl": None,
                "references": q.get("source", "PreTest Psychiatry 14th Ed"),
            })
            pt_count += 1

# Load Generated
gen_dir = os.path.join(BASE, "data", "generated")
gen_count = 0
if os.path.exists(gen_dir):
    for f in sorted(glob.glob(os.path.join(gen_dir, "*.json"))):
        data = json.load(open(f, encoding='utf-8'))
        for q in data:
            all_questions.append(q)
            gen_count += 1

# Write questions.js
questions_js = f"// Auto-generated by build.py — DO NOT EDIT\n"
questions_js += f"// PreTest: {pt_count} | Generated: {gen_count} | Total: {len(all_questions)}\n"
questions_js += f"const DOMAINS = {json.dumps(DOMAINS, ensure_ascii=False, indent=2)};\n\n"
questions_js += f"const QUESTIONS = {json.dumps(all_questions, ensure_ascii=False, indent=2)};\n"

with open(os.path.join(DOCS, "questions.js"), 'w', encoding='utf-8') as f:
    f.write(questions_js)

print(f"Built docs/questions.js: {pt_count} pretest + {gen_count} generated = {len(all_questions)} total")
print(f"Domains: {len(set(q['domain'] for q in all_questions))} active")

# Copy index.html if exists
src_html = os.path.join(BASE, "src", "index.html")
if os.path.exists(src_html):
    shutil.copy2(src_html, os.path.join(DOCS, "index.html"))
    print("Copied src/index.html → docs/index.html")
else:
    print("WARNING: src/index.html not found — create it!")
